### ISSUE TITLE
multi-document-agent example is using old version of Llama-index.  Could it be updated to version 10?

### ISSUE THREAD

**Issue by gabelegorburu** [run-llama/create_llama_projects#32]

**Comment by yw5aj** [comment]
Same issue here:

```
Installing community project: multi-document-agent
Initialized a git repository.


Success! Created multi-agent-rag at /Users/xxx/Downloads/xxx/multi-agent-rag
Now have a look at the README.md (​file:///Users/xxx/Downloads/xxx/multi-agent-rag/README.md​) and learn how to get started.

Aborting installation.
Unexpected error. Please report it as a bug:
 TypeError: Cannot read properties of undefined (reading 'some')
    at createApp (/Users/xxx/.npm/_npx/7bfc2205dda2d438/node_modules/create-llama/dist/index.js:326:56343)
    at async run (/Users/xxx/.npm/_npx/7bfc2205dda2d438/node_modules/create-llama/dist/index.js:326:64521)

```
